# Makefile generated at date
CC = gcc
CFLAGS = -Wall -o3

circmain:	circ1.o circ2.o circmain.o 
	$(CC) $(CFLAGS) -o $@ circ1.o circ2.o circmain.o 

circ1.o: circ1.h circ1.c
circ2.o: circ2.h circ2.c
circmain.o: circ1.h circmain.c
